import { IService } from '~/interfaces';

export const findVendor: IService = {
  id: 'find_vendor',
  name: 'Find Vendor',
  description: [`Retrieve specific vendor by id and their saved details.`],
  endpoint: {
    method: 'get',
    url: '/v1/vendors/{vendor_id}',
    params: [
      {
        required: true,
        attributeId: 'vendor_id',
      },
    ],
    response: {
      type: 'application/json',
      data: {
        data: {
          "id": "21",
        "vendor_id": "2010354",
        "parent_account_id": "bs_1018215",
        "parent_id": "5064",
        "name": "Business ABC",
        "firstName": "",
        "lastName": "",
        "email": "vendor@example.com",
        "address": "25 Business Avenue",
        "city": "Boston",
        "zip": "12345",
        "country": "US",
        "phone": "1-123-455-8765",
        "state": "MA",
        "taxId": "123456789",
        "vatId": "",
        "frequency": "",
        "delay": "0",
        "vendorUrl": "http://mycompany.com",
        "defaultPayoutCurrency": "USD",
        "ipnUrl": "https://ipnaddress.com",
        "vp_fname": "Joe",
        "vp_lname": "Smith",
        "vp_address": "123 Main Street",
        "vp_address2": "",
        "vp_city": "Boston",
        "vp_zip": "12345",
        "vp_country": "US",
        "vp_dob": "9999-09-28",
        "personalIdentificationNumber": "1234",
        "driverLicenseNumber": "561196411",
        "driver_license_issued_by": "0",
        "passportNumber": "",
        "passport_issued_by": "0",
        "vp_email": "principal.vendor@email.com",
        "commissionPercent": "30",
        "payoutType": "ACH",
        "baseCurrency": "USD",
        "minimalPayoutAmount": "50",
        "nameOnAccount": "name of vendor account",
        "bankAccountClass": "CORPORATE",
        "bankAccountType": "CHECKING",
        "bankName": "Bank of America",
        "bankId": "123456789",
        "swiftBic": "",
        "po_address": "1 bank address",
        "po_city": "Boston",
        "po_zip": "12345",
        "po_country": "US",
        "po_state": "MA",
        "bankAccountId": "36628822",
        "iban": "",
        "paymentReference": "Payment for vendor 1234",
        "refundReserve": "200",
        "account_status": "active",
        "payout_status": "active",
        "processing_status": "active",
        "declined_reason": "",
        "last_updated_by": "5064",
        "date_modified": null,
        "date_created": "2024-02-23 08:56:08",
        },
        status: 200,
        message: '',
      },
    },
  },
};
