import { IService } from '~/interfaces';

export const listAllVendors: IService = {
  id: 'list_vendors',
  name: 'List All Vendors',
  description: [`Retrieve All Vendors and their saved details.`],
  endpoint: {
    method: 'get',
    url: '/v1/vendors',

    response: {
      type: 'application/json',
      data: {
        data: [
          {
            "id": "2",
            "vendor_id": "988575",
            "parent_account_id": "bs_10435358",
            "parent_id": "5064",
            "name": "Test1, Vendor",
            "firstName": "Vendor",
            "lastName": "Test1",
            "email": "mariganesh@easymerchant.io",
            "address": "",
            "city": "",
            "zip": "",
            "country": "us",
            "phone": "",
            "state": "AL",
            "taxId": "",
            "vatId": "",
            "frequency": "",
            "delay": "0",
            "vendorUrl": "",
            "defaultPayoutCurrency": "USD",
            "ipnUrl": "",
            "vp_fname": "Jim",
            "vp_lname": "Jim",
            "vp_address": "sadsasad",
            "vp_address2": "",
            "vp_city": "TEst",
            "vp_zip": "12345",
            "vp_country": "us",
            "vp_dob": "2021-09-28",
            "personalIdentificationNumber": "12345",
            "driverLicenseNumber": "",
            "driver_license_issued_by": "",
            "passportNumber": "",
            "passport_issued_by": null,
            "vp_email": "asdsa@rwsas.com",
            "commissionPercent": "10",
            "payoutType": "ACH",
            "baseCurrency": "USD",
            "minimalPayoutAmount": "0",
            "nameOnAccount": "Test Account",
            "bankAccountClass": "PERSONAL",
            "bankAccountType": "CHECKING",
            "bankName": "Test Bank",
            "bankId": "123456789",
            "swiftBic": "",
            "po_address": "",
            "po_city": "",
            "po_zip": "12345",
            "po_country": "us",
            "po_state": "AL",
            "bankAccountId": "1234567",
            "iban": "",
            "paymentReference": "",
            "refundReserve": "0",
            "account_status": "active",
            "payout_status": "active",
            "processing_status": "active",
            "declined_reason": "",
            "last_updated_by": "5064",
            "date_modified": null,
            "date_created": "2022-02-22 09:35:35",
          },
        ],
        status: 200,
        message: '',
      },
    },
  },
};
